#!/usr/bin/env bash

[[ "${1,,}" != +(\-)@(h)?(elp) ]] || {
	echo -e "\e[1;32mNAME\e[0;32m:\e[0m"
	echo '   bashed - omni-directional bash-builtin-centric transmutations'
	echo -e "\e[1;32mUSAGE\e[0;32m:\e[0m"
	echo -e "   Apply EXPRESSION(s) to each line of input passed through a pipe [\e[1;4;33mAND/OR\e[0m] read from a file:"
	echo -e "         \`\e[1;37m[ input... | ] bashed  'EXPRESSION(s)'...  [FILE]\e[0m\`"
	echo -e "                                                 \e[0;37m# if supplied, FILE must be the final argument.\e[0m"
	echo -e "   \e[1;4;33mOR\e[0m passed verbatim as \`\$1\`:"
	echo -e "         \`\e[1;37mbashed 'INPUT STRING' 'EXPRESSION(s)'... \e[0m\`"
	echo ""
	[[ "${2,,}" != *(\-)@(all|expr?(ession)|full|syntax|v?(erbose)) ]] && echo -e " * \e[3mFor info on EXPRESSION syntax, run:\e[0m \`\e[1;37mbashed -h all\e[0m\`\n" || {
		echo -e " * \e[1;33mEXPRESSIONs\e[0m are applied"
		echo '         - to each line of input (unless otherwise specified)'
		echo '         - in the order they were supplied,'
		echo ""
		echo -e "\e[1;32mBASH BUILT-IN EXPANSIONS\e[0;32m:\e[0;37m (do what you'd expect)\e[0m"
		echo "  ':N'        : from Nth to last char(s)"
		echo "  '::N'       : from first to Nth char(s)"
		echo "  ':N:N'      : from Nth to Nth char(s)"
		echo "  '%...*'     : preceding last of ..."
		echo "  '%%...*'    : preceding any of ..."
		echo "  '#*...'     : after first of ..."
		echo "  '##*...'    : after any of ..."
		echo "  '/w/[e]'    : replace first of 'w' with ['e']"
		echo "  '//w/[e]'   : replace any of 'w' with ['e']"
		echo "  '^'         : make first character Uppercase."
		echo "  '^^'        : make all characters UPPERCASE."
		echo "  ','         : make first character lOWERCASE."
		echo "  ',,'        : make all characters lowercase."
		echo "  '~[abc]'    : swap case of first [(detected) optionally specified] character."
		echo "  '~~[abc]'   : swap case of all [(detected) optionally specified] characters."
		echo -e "                \e[0;37m# if [character(s)] are specified but none are detected, does nothing\e[0m"
		echo -e "                \e[0;37m#  otherwise, behaves normally.\e[0m"
		echo ""
		echo -e "\e[1;32mFILTERING & CONDITIONAL EXPRESSIONS\e[0;32m:\e[0m"
		echo "  '??[zdploukfnsexy]'       : test every line ( \` [[ -[zdploukfnsexy] <...> ]] \` )"
		echo "  '?![zdploukfnsexy]'       : test every line ( \` [[ ! -[zdploukfnsexy] <...> ]] \` )"
		echo "  '??[zdploukfnsexy].{EXPR}': Apply EXPR to lines which pass a <[[ -<> test ]]>"
		echo "  '?![zdploukfnsexy].{EXPR}': Apply EXPR to lines which fail a <[[ -<> test ]]>"

		echo "  TODO: nested circuits of the above by chaining, like discrete && chains"

		echo "  '??[=|~]_'        : Supress lines not [matching|containing] <_>"
		echo "  '?![=|~]_'        : Supress lines [matching|containing] <_>"
		echo "  '??[=|~]_.{EXPR}' : Apply EXPR to lines [matching|containing] <_>"
		echo "  '?![=|~]_.{EXPR}' : Apply EXPR to lines not [matching|containing] <_>"
		echo -e "      \e[0;37m# examples:\e[0m"
		echo -e "      \e[0;37m#\e[0m  \`... | bashed '??=*whatev*' \`\e[0;37m (supress lines not matching *'whatev'*)\e[0m"
		echo -e "      \e[0;37m#\e[0m  \`... | bashed '?!~whatev' \`\e[0;37m (supress lines containing 'whatev')\e[0m"
		echo -e "      \e[0;37m#\e[0m  \`... | bashed '??~whatev.{(_).}' \`\e[0;37m (prepend all lines containing 'whatev' with '_')\e[0m"
		echo ""
		echo -e "\e[1;32mMISCELLANEOUS EXPRESSIONS\e[0;32m:\e[0m"
		echo '  -[BP],'
		echo '    --before,'
		echo '    --prepend _'
		echo "          '(_).'    : Prepend each line with _"
		echo ""
		echo '  -A,'
		echo '   --after,'
		echo '   --append _'
		echo "        '.(_)'      : Append _ to each line"
		echo ""
		echo '   -[fFcC],         : POSIX color codes (defaults to `\e[0;...`(typically 30-40),'
		echo '   --[color,font]=                       but any `\e[...` expression should work)'
		echo -e "                   \e[0;37m# examples:\e[0m"
		echo -e "                   \e[0;37m#\e[0m   \`... | bashed -c '1;33;3' \`"
		echo -e "                   \e[0;37m#\e[0m   \`... | bashed --color=33 \`"
		echo -e "                    \e[0;37m(*) supply font effects last as any remaining EXPRESSIONS are likely to remove them.\e[0m"
		echo ""
		echo "  ':*',          : Extends the \`:N:N\` substring expansions to allow any string/[pattern]. Carve away."
		echo -e "   '::*',         \e[0;37m# examples:\e[0m"
		echo -e "    ':*:*',       \e[0;37m#\e[0m   \`... | bashed ':[wW]::hat[eE]ver' \`"
		echo -e "     ':*::*'      \e[0;37m#\e[0m   \`... | bashed ':ex:[ABC123]' \`"
		echo -e "                  \e[0;37m#\e[0m   \`... | bashed '::[aAbBcC]' \`"
		echo ""
		echo "  \"//_/*\$'\\n'*\" : Replace each of '_' with *newline*"
		echo ""
		echo "  \"//\$'\\n'/*\"   : Remove or replace newlines with [*| ]"
		echo ""
		echo " '{N}.EXPR'     : Repeatedly apply EXPR(any other EXPRESSION) N times."
		echo -e "                 \e[0;37m# example:\e[0m"
		echo -e "                 \e[0;37m# trim up to third occurance of ['/'or'\']\e[0m"
		echo "                 $(echo -e "\e[0;37m#\e[0m")   \`... | bashed '{3}."'#*[\/\\]'"' \`"
		echo -e "\n\e[1;33m ...ohh and  bc  is pretty much a first-class-citizen now too.\n"
		#    ${parameter@operator}
		#              Parameter transformation.  The expansion is either a transformation of the value of parameter or infor‐
		#              mation about parameter itself, depending on the value of operator.  Each operator is a single letter:
		#
		#              U      The expansion is a string that is the value of parameter with  lowercase  alphabetic  characters
		#                     converted to uppercase.
		#
		#              u      The  expansion  is a string that is the value of parameter with the first character converted to
		#                     uppercase, if it is alphabetic.
		#
		#              L      The expansion is a string that is the value of parameter with  uppercase  alphabetic  characters
		#                     converted to lowercase.
		#
		#              Q      The  expansion  is a string that is the value of parameter quoted in a format that can be reused
		#                     as input.
		#
		#              E      The expansion is a string that is the value of parameter with  backslash  escape  sequences  ex‐
		#                     panded as with the $'...' quoting mechanism.
		#
		#              P      The expansion is a string that is the result of expanding the value of parameter as if it were a
		#                     prompt string (see PROMPTING below).
		#
		#              A      The expansion is a string in the form of an assignment statement or  declare  command  that,  if
		#                     evaluated, will recreate parameter with its attributes and value.
		#
		#              K      Produces  a  possibly-quoted version of the value of parameter, except that it prints the values
		#                     of indexed and associative arrays as a sequence of quoted key-value pairs (see Arrays above).
		#
		#              a      The expansion is a string consisting of flag values representing parameter's attributes.
		#
		#              If parameter is @ or *, the operation is applied to each positional parameter in turn, and  the  expan‐
		#              sion  is  the resultant list.  If parameter is an array variable subscripted with @ or *, the operation
		#              is applied to each member of the array in turn, and the expansion is the resultant list.
		#
		#              The result of the expansion is subject to word splitting and pathname expansion.
	}
	exit 0
}

declare -g String
declare -ga Strings

exactly() {
	_0() { [[ "$String" == ${@} ]] ; }
	_1() { [[ "$String" != ${@} ]] ; }
	_$1 "${@:2}"
}

fuzzily() {
	_0() { [[ "${String,,}" == *"${@,,}"* || "${@,,}" == *"${String,,}"* || "$String" == *${@}* || ${@} == *"$String"* ]] ; }
	_1() { [[ "${String,,}" != *"${@,,}"* && "${@,,}" != *"${String,,}"* && "$String" != *${@}* && ${@} != *"$String"* ]] ; }
	_${1} "${@:2}"
}

whats() { _0() { eval [[ $1 "$String" ]] ; }; _1() { eval [[ ! $1 "$String" ]] ; }; _$1 "-$2"; }

dp() { local -i x; while read item ; do Array[${#Array[@]}]="$item" ; done < <(for((;++x<=$#;)){ echo "${!x}" ; } ; [ -t 0 ] || cat - ) ; local IFS=\| ; echo "${Array[*]}" ; }

toLast() {
	_b() { : "${2%$1*}" ; [[ "$1" != \[*\] ]] && String="${2::${#_}+${#1}}" || String="${2::${#_}+1}" ; }
	_a() { : "${String%%$1*}" ; _b "$2" "${String:${#_}}" ; }
	_a "$1" "$2"
}
toFirst() {
	_b() { : "${2%%$1*}" ; [[ "$1" != \[*\] ]] && String="${2::${#_}+${#1}}" || String="${2::${#_}+1}" ; }
	_a() { : "${String%%$1*}" ; _b "$2" "${String:${#_}}" ; }
	_a "$1" "$2"
}

dundre() { [[ "$String" != *$1* ]] || String="${String%%${String#*$1}*}" ; }

notMath() { [[ "$@" =~ [^0-9\(\)\.\ \-\+\*\/\%\<\=] ]]; }
mayuth() { noMath "$@" || return $(echo "$@" | bc); }
# WIP
# [\<\=\!\>][0-9\ \(\!\.\-\+\*\%\<\=\>\)]*\ \.\{*\}) doif="${!a#*\ \.\{}" && mayuth "${String//[!0-9\(\.\-\+\*\%\<\=\>\)\ ]/}" "${!a//[!0-9\(\.\-\+\*\%\<\=\>\)\ ]/}" || { Argz=( "$String" ${doif:: -1} ) && for ((z=0;z<${#Argz[@]};z++)); do string=$(echo "${string:-$String}" | $FUNCNAME "${Argz[z]}") ; done && String="$string" ; unset string Argz[*] ; } ;;
OtherPipe() {
	local -a Argz=() string=()
	while read -r line ; do
		String="${line@Q}"
		for ((a=1;a<=$#;a++)); do
			case "${!a}" in
			*\/*"$'\n'"*\/*) if [[ "${!a##*\/}" == *[!\ ]* ]]; then cat - | dp "$String" | $FUNCNAME "//\|/'${!a##*\/}'" "${@:$a+1}" ; else { echo "$String" ; cat - ; } | xargs | $FUNCNAME "${@:$a+1}" ; fi ; unset String ;;
			\/*[!\/]*\/*"$'\n'"*) eval Strings\=\( $(eval printf '%q' \"\$\{String"${!a}"\}\") \) ; unset String ;;
			[\_\.]\(*\)) String="$String${!a:2: -1}" ;;
			\-[bB]*|\-\-[bp][er][fe][op][re][en]*) [[ -z "${!a//*\=*}" ]] || ((++a)) ; String="${!a#*\=}$String" ;;
			\(*\)[\.\_]) String="${!a:1: -2}$String" ;;
			\-[aA]|\-\-a[pf][pt][e][nr]*) [[ -z "${!a/*\=*/}" ]] || ((++a)) ; String="$String${!a#*\=}" ;;
			\-[cCfF]|'--color'*|'--font'*) [[ -z "${!a//*\=*/}" ]] || ((++a)) ; String=$(echo -e "\e[${!a#*\=}m$String\e[0m") ;;
			\?\?\=*[!\}]) exactly "0" "${!a:3}" || { unset String ; break ; } ;;
			\?\!\=*[!\}]) exactly "1" "${!a:3}" || { unset String ; break ; } ;;
			\?\?\~*[!\}]) fuzzily "0" "${!a:3}" || { unset String ; break ; } ;;
			\?\!\~*[!\}]) fuzzily "1" "${!a:3}" || { unset String ; break ; } ;;
			[\(\+\-\/\*\%\)][0-9\.\(\+\-\ \/\*\%\)]*) [[ "$line" == *\)\.* || "$line" == *\.\)* ]] || String="$(echo "${String//[!0-9\(\.\-\+\*\%\<\=\>\)\ ]/} ${!a//[!0-9\(\.\-\+\*\%\<\=\>\)\ ]/}" | bc -l)" ;;
			[\<\=\!\>][0-9\ \(\!\.\-\+\*\%\<\=\>\)]*) [[ "$line" == *\)\.* || "$line" == *\.\)* ]] || { mayuth "! ${String//[!0-9\(\.\-\+\*\%\<\=\>\)\ ]/}" "${!a//[!0-9\(\.\-\+\*\%\<\=\>\)\ ]/}" || { unset String; break; }; } ;;
			[UuLQEPAKa]|\@[UuLQEPAKa]) eval String="\${String@${!a#*\@}}" ;;
			\?\?[zdploukfnsexy]) whats "0" "${!a:2:1}" || { unset String ; break ; } ;;
			\?\![zdploukfnsexy]) whats "1" "${!a:2:1}" || { unset String ; break ; } ;;
			\?\?[zdploukfnsexy]\ \.\{*\}) doif="${!a#*\ \.\{}" && whats "1" "${!a:2: -${#doif}-2}" || { Argz=( "$String" ${doif:: -1} ) && for ((z=0;z<${#Argz[@]};z++)); do string=$(echo "${string:-$String}" | $FUNCNAME "${Argz[z]}") ; done && String="$string" ; unset string Argz[*] ; } ;;
			\?\![zdploukfnsexy]\ \.\{*\}) doif="${!a#*\ \.\{}" && whats "0" "${!a:2: -${#doif}-2}" || { Argz=( "$String" ${doif:: -1} ) && for ((z=0;z<${#Argz[@]};z++)); do string=$(echo "${string:-$String}" | $FUNCNAME "${Argz[z]}") ; done && String="$string" ; unset string Argz[*] ; } ;;
			\?\?\=*\ \.\{*\}) doif="${!a#*\ \.\{}" && exactly "1" "${!a:3: -${#doif}-2}" || { Argz=( "$String" ${doif:: -1} ) && for ((z=0;z<${#Argz[@]};z++)); do string=$(echo "${string:-$String}" | $FUNCNAME "${Argz[z]}") ; done && String="$string" ; unset string Argz[*] ; } ;;
			\?\!\=*\ \.\{*\}) doif="${!a#*\ \.\{}" && exactly "0" "${!a:3: -${#doif}-2}" || { Argz=( "$String" ${doif:: -1} ) && for ((z=0;z<${#Argz[@]};z++)); do string=$(echo "${string:-$String}" | $FUNCNAME "${Argz[z]}") ; done && String="$string" ; unset string Argz[*] ; } ;;
			\?\?\~*\ \.\{*\}) doif="${!a#*\ \.\{}" && fuzzily "1" "${!a:3: -${#doif}-2}" || { Argz=( "$String" ${doif:: -1} ) && for ((z=0;z<${#Argz[@]};z++)); do string=$(echo "${string:-$String}" | $FUNCNAME "${Argz[z]}") ; done && String="$string" ; unset string Argz[*] ; } ;;
			\?\!\~*\ \.\{*\}) doif="${!a#*\ \.\{}" && fuzzily "0" "${!a:3: -${#doif}-2}" || { Argz=( "$String" ${doif:: -1} ) && for ((z=0;z<${#Argz[@]};z++)); do string=$(echo "${string:-$String}" | $FUNCNAME "${Argz[z]}") ; done && String="$string" ; unset string Argz[*] ; } ;;
			\:[!0-9\:]*|\:\:[!0-9]*)
				if [[ "${!a}" == \:\:+([!\:])\:\:* ]]; then
					while read ence ; do [[ -z "$ence" ]] || dundre "$ence" ; done < <(echo "${!a//'::'/$'\n'}" )
				else
					if [[ "${!a}" == \:+([!\:])\:+([!\:]) ]]; then
						x="${!a:1}" && y="${x#*\:}" && toFirst "${x%%\:*}" "$y"
						unset x y
					elif [[ "${!a}" == \:+([!\:])\:\:* ]]; then
						x="${!a:1}" && y="${x#*\:\:}" && toLast "${x%%\:*}" "$y"
						unset x y
					else
						if [[ ${!a:1:1} == \: ]]; then
							dundre "${!a:2}"
						else
							[[ "$String" != *${!a:1}* ]] || String="${String#*${String%%${!a:1}*}}"
						fi
					fi
				fi
				;;
			*)
				if [[ "${!a}" == \{+([[:digit:]])\}\.* ]]; then
					rp="${!a%%\}*}" && ((rt=(${rp:1} + 0)))
					for ((ri=0;ri<rt;ri++)); do
						String=$(echo "$String" | $FUNCNAME "${!a#*\}\.}")
					done
					unset rp rt ri
				else
					eval String\=\$\{String"${!a}"\}
				fi
			esac
			if (( ${#Strings[@]} != 0 )); then
				for ((i=0;i<${#Strings[@]};i++)); do
					echo "${Strings[i]}"
				done | $0 "${@:$a+1}"
				unset Strings[*]
				continue
			fi
			(( ${#String} > 0 )) || break
		done
		(( ${#String} == 0 )) || echo "$String"
	done < <(cat - )
}

[[ -f "${!#-1}" && $# -gt 1 ]] && { [ -t 0 ] && { cat "${!#-1}" | OtherPipe "${@:1:$#-1}" ; } || { cat "${!#-1}" - | OtherPipe "${@:1:$#-1}" ; } ; } || { [ -t 0 ] && { echo "$1" | OtherPipe "${@:2}" ; } || { cat - | OtherPipe "${@}" ; } ; } 2>/dev/null
